name: task_alert_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.2
  google_fonts: ^6.1.0
  flutter_vector_icons: ^2.0.0
  timezone: ^0.9.0
  shared_preferences: ^2.2.2
  http: ^1.4.0
  provider: ^6.1.2
  flutter_local_notifications: ^17.0.0
  intl: ^0.20.2
  uuid: ^4.3.3
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.6
  firebase_messaging: ^14.7.15
  easy_localization: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dependency_overrides:
  shared_preferences_android: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
